fix: run in both linux & macos

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -19,12 +19,19 @@ jobs:
       # run: ls bin *_test* | xargs -L 1 -d '\n'
       run: |
         BIN_DIR="./bin"
+                  
+        # For each executable file in the folder
+        find "$BIN_DIR" -type f -name '*_test' -print0 | while IFS= read -r -d $'\0' bin_path; do
+          # Skip non-executable file
+          [ -x "$bin_path" ] || continue
 
-        find "$BIN_DIR" -type f -name '*_test' -executable -print0 | while IFS= read -r -d $'\0' binary_path; do
-          echo "Running: $binary_path"
-          "$binary_path" # Execute the binary
+          # Execute the binary
+          echo "Running: $bin_path"
+          "$bin_path"
+
+          # Check result
           if [ $? -ne 0 ]; then
-            echo "Error running $binary_path"
-            exit 1 # Exit if a binary fails
+            echo "Error running $bin_path"
+            exit 1
           fi
         done
